[project]
name = "rinha-2026-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.136.1",
    "uvicorn>=0.46.0",
    "faiss-cpu>=1.9.0",
    "numpy>=2.0.0",
    "ijson>=3.3.0",
    "uvloop>=0.21.0",
    "httptools>=0.6.0",
]
